project:
  type: website

website:
  title: "docs"
  navbar:
    type: sticky
    position: top
    background: success
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



